### ISSUE TITLE
Not working in 1.20

### ISSUE THREAD

**Issue by Zund0** [Goby56/wakes#3]
It doesn't say why, but it does say it needs version 1.20.1, shouldn't it work on 1.20 too?

**Comment by Goby56** [comment]
While it theoretically should work on 1.20 as well, the mod warns you of an outdated version just to be sure. In some cases this limitation can be overwritten by editing a file inside the mod. [This tutorial](https://www.youtube.com/watch?v=GWB8loTTfw0) shows you how to.

I managed to run the mod by changing the required version to `>=1.20.0` so in future versions of the mod I'll try to broaden the available Minecraft versions. If you can't wait for that check out the tutorial.

**Comment by rainysux** [comment]
Hey I just tried changing the version manually and it just crashes when I enter a world, I can open the game though.

**Comment by Goby56** [comment]
Could you send the crash logs? Please use something like [Pastebin](https://pastebin.com/)

**Comment by rainysux** [comment]
I have it in a modpack of mine so maybe it can be due to a incompatibility possibly.

---- Minecraft Crash Report ----
// Uh... Did I do that?
 
Time: 2023-07-07 02:42:14
Description: Exception in server tick loop
 
java.lang.NoClassDefFoundError: me/lucko/fabric/api/permissions/v0/Options
	at xaero.pac.common.server.player.permission.impl.FabricPermissionsSystem.getIntPermission(FabricPermissionsSystem.java:50)
	at xaero.pac.common.server.claims.player.ServerPlayerClaimInfoManager.getPlayerBaseLimit(ServerPlayerClaimInfoManager.java:148)
	at xaero.pac.common.server.claims.ServerClaimsManager.getPlayerBaseForceloadLimit(ServerClaimsManager.java:354)
	at xaero.pac.common.server.claims.forceload.ForceLoadTicketManager.updateTicketsFor(ForceLoadTicketManager.java:131)
	at xaero.pac.common.server.player.PlayerLoginHandler.handlePreWorldJoin(PlayerLoginHandler.java:61)
	at xaero.pac.common.server.player.data.api.ServerPlayerDataAPI.from(ServerPlayerDataAPI.java:87)
	at xaero.pac.common.event.CommonEvents.onPlayerLogIn(CommonEvents.java:168)
	at xaero.pac.common.event.CommonEventsFabric.onPlayerLogIn(CommonEventsFabric.java:132)
	at net.minecraft.class_3324.handler$doe000$openpartiesandclaims$onPlaceNewPlayer(class_3324.java:4528)
	at net.minecraft.class_3324.method_14570(class_3324.java:307)
	at net.minecraft.class_3248.method_33800(class_3248.java:131)
	at net.minecraft.class_3248.method_14384(class_3248.java:118)
	at net.minecraft.class_3248.redirect$boi000$fabric-networking-api-v1$handlePlayerJoin(class_3248.java:563)
	at net.minecraft.class_3248.method_18784(class_3248.java:68)
	at net.minecraft.class_2535.method_10754(class_2535.java:254)
	at net.minecraft.class_3242.method_14357(class_3242.java:172)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:908)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: me.lucko.fabric.api.permissions.v0.Options
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 22 more
 
 
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
 
-- System Details --
Details:
	Minecraft Version: 1.20
	Minecraft Version ID: 1.20
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2493707424 bytes (2378 MiB) / 5167382528 bytes (4928 MiB) up to 11811160064 bytes (11264 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 3700X 8-Core Processor             
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.59
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce GTX 1660 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2182
	Graphics card #0 versionInfo: DriverVersion=31.0.15.2824
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 27029.14
	Virtual memory used (MB): 19496.59
	Swap memory total (MB): 10698.85
	Swap memory used (MB): 1363.79
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx11G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		adventurez: AdventureZ 1.4.18
		ambientsounds: AmbientSounds 5.2.20
		architectury: Architectury 9.0.8
		autohud: Auto HUD 6.1+1.20
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.8
			yaclx: YetAnotherConfigLibExtensions 1.2+1.20
		bclib: BCLib 3.0.10
			wunderlib: WunderLib 1.1.3
		betterarcheology: Better Archeology 1.0.2
		bettercombat: Better Combat 1.7.2+1.20.1
		betterdeserttemples: YUNG's Better Desert Temples 1.20-Fabric-3.0
			org_reflections_reflections: reflections 0.10.2
		betterdungeons: YUNG's Better Dungeons 1.20-Fabric-4.0
		betterend: Better End 4.0.7
		betterfortresses: YUNG's Better Nether Fortresses 1.20-Fabric-2.0
		betterfpsdist: Better FPS distance Mod 1.20.1-2.7
		bettermineshafts: YUNG's Better Mineshafts 1.20-Fabric-4.0
		betternether: Better Nether 9.0.7
		betteroceanmonuments: YUNG's Better Ocean Monuments 1.20-Fabric-3.0
		betterstrongholds: YUNG's Better Strongholds 1.20-Fabric-4.0
		betterthirdperson: Better Third Person 1.9.0
		betterwitchhuts: YUNG's Better Witch Huts 1.20-Fabric-3.0
		carrier: Carrier 1.12.0
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.7
			cardinal-components-base: Cardinal Components API (base) 5.2.1
			cardinal-components-entity: Cardinal Components API (entities) 5.2.1
		cavedust: Cave Dust 1.4.1
			kirin: Kirin UI 1.15.0
		cloth-config: Cloth Config v11 11.0.99
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 6.57
		creativecore: CreativeCore 2.10.24
			net_minecraftforge_eventbus: eventbus 6.0.3
		creeperoverhaul: Creeper Overhaul 3.0.1
		dawn: Dawn API 5.0.0
			terraform-shapes-api-v1: Terraform Shapes API (v1) 7.0.1
			terraform-wood-api-v1: Terraform Wood API (v1) 7.0.1
		deathlog: DeathLog 0.3.2+1.20
		dungeons_arise: When Dungeons Arise 2.1.56.1
		dynamicfps: Dynamic FPS 2.4.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		dynmus: Dynamic Music 2.3.1+1.20
		easyanvils: Easy Anvils 7.0.0
		easymagic: Easy Magic 7.0.0
		eatinganimationid: Eating Animation 1.9.4+1.20
		elementa: Elementa 590
		endrem: End Remastered 5.2.2
		entity_model_features: Entity Model Features 0.2.11
		entity_texture_features: Entity Texture Features 4.4.4
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling-Fabric 1.6.2-mc1.20
		essential: Essential 12933+deploy-staging+gf941de5ac
		essential-container: essential-container 1.0.0
			essential-loader: essential-loader 1.2.0
		exlinefurniture: Exline's Furniture 2.6.0
		fabric-api: Fabric API 0.83.1+1.20.1
			fabric-api-base: Fabric API Base 0.4.29+b04edc7a77
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.34+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b77
			fabric-block-api-v1: Fabric Block API (v1) 1.0.9+e022e5d177
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.39+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.20+b3afc78b77
			fabric-command-api-v1: Fabric Command API (v1) 1.2.32+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.11+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.49+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.61+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.7+b3afc78b77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.3+b3afc78b77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.1.11+b3afc78b77
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.51+b3afc78b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.21+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.0+b3afc78b77
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.61+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.26+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.7+b3afc78b77
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.20+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.37+b3afc78b77
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.41+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.6+b3afc78b77
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.47+b3afc78b77
			fabric-models-v0: Fabric Models (v0) 0.3.35+b3afc78b77
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.8+b3afc78b77
			fabric-networking-v0: Fabric Networking (v0) 0.3.48+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.0.6+b3afc78b77
			fabric-particles-v1: Fabric Particles (v1) 1.0.28+b3afc78b77
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.18+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.2.6+b3afc78b77
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.0.1+b3afc78b77
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.3.1+b3afc78b77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.44+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.33+b3afc78b77
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.26+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.47+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.6+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.7+f7923f6d77
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.6+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.27+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.2.2+b3afc78b77
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.2.0+b3afc78b77
		fabric-language-kotlin: Fabric Language Kotlin 1.10.0+kotlin.1.9.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.21.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.2
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.2
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.1
		fabricloader: Fabric Loader 0.14.21
		fallingleaves: Falling Leaves 1.15.1+1.20.1
		fallingtree: FallingTree 4.0.0
		ferritecore: FerriteCore 6.0.0
		forgeconfigapiport: Forge Config API Port 7.0.0
		friendsandfoes: Friends&Foes 1.9.2
		fullturtlearmor: Full Turtle Armor 1.5
		fwaystones: Fabric Waystones 3.1.2+mc1.20
		geckolib: Geckolib 4.2
			com_eliotlash_mclib_mclib: mclib 20
		handcrafted: Handcrafted 2.3.2
		immersive_paintings: Immersive Paintings 0.6.1+1.20
		iris: Iris 1.6.4
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 14.0.0.11
		krypton: Krypton 0.2.3
			com_velocitypowered_velocity-native: velocity-native 3.2.0-SNAPSHOT
		lazydfu: LazyDFU 0.1.3
		lithium: Lithium 0.11.2
		lostfeatures: Lost Features 0.7.1
		memoryleakfix: Memory Leak Fix 1.1.1
		midnightlib: MidnightLib 1.4.1
		minecraft: Minecraft 1.20
		mo_glass: Mo Glass 1.6.1-MC1.20
		mobs_attempt_parkour: Mobs Attempt Parkour 0.5-1.20
			maelstrom_library: Maelstrom Library 1.6-1.20
		modmenu: Mod Menu 7.1.0
		moonlight: Moonlight 1.20-2.5.12
		more_armor_trims: More Armor Trims 1.1.0-1.20.1
		moremobvariants: More Mob Variants 1.2.2
		mousetweaks: Mouse Tweaks 2.25
		mr_vanilla_refresh: Vanilla Refresh 1.4.16
		naturescompass: Nature's Compass 1.20-2.2.2-fabric
		no-shield-delay: No Shield Delay 1.0.0
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		notenoughanimations: NotEnoughAnimations 1.6.4
		openpartiesandclaims: Open Parties and Claims 0.19.0
		org_jetbrains_annotations: annotations 13.0
		owo: oωo 0.11.1+1.20
			blue_endless_jankson: jankson 1.2.2
		player-animator: Player Animator 1.0.2-rc1+1.20
		presencefootsteps: Presence Footsteps 1.9.0
		promenade: Promenade 4.1.0
			biolith: Biolith 1.0.0-alpha.7
				terraform-surfaces-api-v1: Terraform Surfaces API (v1) 7.0.0-beta.1
		puzzleslib: Puzzles Lib 7.0.9
		rainglow: Rainglow 1.1.2+mc1.20.1
			spruceui: SpruceUI 5.0.0+1.20
		realcamera: Real Camera 0.5.3-beta
		rebind_narrator: Rebind Narrator 2.0.1
		regions_unexplored: Regions Unexplored 0.4.1+1.20
		repurposed_structures: Repurposed Structures 7.0.0+1.20-fabric
		resourcefulconfig: Resourcefulconfig 2.0.0
		resourcefullib: Resourceful Lib 2.0.8
			com_teamresourceful_yabn: yabn 1.0.3
		skinlayers: 3d Skin Layers 1.5.3-mc1.20
		snuffles: Snuffles 1.0.0+1.20
		sodium: Sodium 0.4.10+build.27
		soulsweapons: Marium's Soulslike Weaponry 0.9.9.6-1.20-fabric
		sound_physics_remastered: Sound Physics Remastered 1.20-1.1.1
		spark: spark 1.10.42
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		stackrefill: Stack Refill 4.0
		stoneworks: Stoneworks 7.0.1
		swampier_swamps: Swampier Swamps 1.20-4.0.0
		terrablender: TerraBlender 3.0.0.163
		universalcraft: UniversalCraft 277
		vanilla_degus: Vanilla Degus 1.4.0
		varietyapi: VarietyAPI 1.0
		varietyaquatic: Variety Aquatic 1.0.4.8
		veinmining: Vein Mining 1.2.0+1.20.1
			spectrelib: SpectreLib 0.13.13+1.20.1
		vigilance: Vigilance 284
		visualworkbench: Visual Workbench 7.0.0
		wakes: Wakes 0.1.4
		xaerominimap: Xaero's Minimap 23.5.0
		xaeroworldmap: Xaero's World Map 1.30.6
		yet_another_config_lib_v3: YetAnotherConfigLib 3.0.2+1.20
			com_twelvemonkeys_common_common-image: common-image 3.9.4
			com_twelvemonkeys_common_common-io: common-io 3.9.4
			com_twelvemonkeys_common_common-lang: common-lang 3.9.4
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.9.4
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.9.4
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.9.4
		yungsapi: YUNG's API 1.20-Fabric-4.0-beta0
			org_javassist_javassist: javassist 3.29.2-GA
	Loaded Shaderpack: OverimaginedShaders_r1.2.1-1.0.zip
		Profile: Custom (+13 options changed by user)
	NEC status: No NEC detected
	Server Running: true
	Player Count: 1 / 8; [class_3222['rainysux'/59, l='ServerLevel[Alyssa Jose Honey Moon]', x=-299.24, y=74.00, z=263.76]]
	Data Packs: vanilla, fabric, file/Terralith_1.20_v2.4.0.zip, file/Dungeons and Taverns v2.1.3.zip, file/pk-better-compass-v-2-0-2.zip, file/pk-racks-v-2-2-0.zip, file/sherd-tweaks.zip, file/Better+Bundle+v1.3.1(mc-1.20).zip, file/thebastionoverhaul-v1-0.zip, file/Botanic+Pots+[datapack]+v1.0.2.zip, file/hearths-v1.0.0-pf15.zip
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: fabric-loader-0.14.21-1.20

**Comment by rainysux** [comment]
Just tried it by itself in a seperate mod profile and it does work, might actually be an incompatibility issue in my end.

**Comment by Goby56** [comment]
Yeah from the crash logs it seems as though wakes has nothing to do with it. From what I can tell it has something to do with one of xaero's map mods. 

Although the crash was not caused by Wakes, this issue did bring to light the fact that the mod actually works for 1.20 as well.  The next release will therefore most likely support both 1.20 and 1.20.1.
